CREATE DATABASE game_test DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
USE game_test;

CREATE TABLE server_info (
  name VARCHAR(128) NOT NULL,
  value text NOT NULL,
  PRIMARY KEY (name)
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin;

INSERT INTO server_info VALUES('createTime', CURRENT_TIMESTAMP);
INSERT INTO server_info VALUES('dbid', '10000');

CREATE TABLE players (
  id BIGINT NOT NULL AUTO_INCREMENT,
  accountId VARCHAR(128) NOT NULL,
  channelId INT NOT NULL DEFAULT 0,
  name VARCHAR(64) NOT NULL,
  sex INT NOT NULL DEFAULT 1,
  level INT NOT NULL DEFAULT 1,
  recordInfo MEDIUMTEXT NOT NULL DEFAULT "",
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  lastPlayedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (accountId),
  UNIQUE KEY (name)
) ENGINE=InnoDB AUTO_INCREMENT=1000000 ROW_FORMAT=DYNAMIC CHARACTER SET utf8 COLLATE utf8_bin;



