//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LuaContainerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(LuaContainer), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("GetLuaFunction", GetLuaFunction);
		L.RegFunction("CallMethod", CallMethod);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLuaFunction(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaContainer obj = (LuaContainer)ToLua.CheckObject<LuaContainer>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			LuaInterface.LuaFunction o = obj.GetLuaFunction(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallMethod(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			LuaContainer obj = (LuaContainer)ToLua.CheckObject<LuaContainer>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			obj.CallMethod(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

